### ISSUE TITLE
v1.5.1 - default compression settings for oxipng is too high for low end VMs

### ISSUE THREAD

**Issue by Identity9165** [Blobfolio/blob-image#1]
Environment: 
Ubuntu 16.04 LTS DigitalOcean Droplet 1 vCPU - 1GB RAM
Oxipng 2.2.1
MozJPEG 3.3.1
blob-image 1.5.1
--
since it's not multithreaded env. I'm using
blob-image -c *

JPEGs work fine but PNG optimization is not feasible with current optimization settings for low end VMs since its causing 100% CPU usage and actually I never got any result via blob-image. I can see that the argument passed is using -o 4 but oxipng uses -o 2 for default installation and works fine when used standalone. Do you suggest any workaround or did I missed something on blob-image arguments documentation?

Thanks for the cool script and thanks in advance for any help.

**Comment by joshstoik1** [comment]
Hi @msc1,

It is actually the `-Z` flag in the Oxipng command that is dragging things to a crawl for you. That flag enables Zopfli compression, which helps reduce file sizes even further, but there's a catch: it requires significantly more time and CPU to compute.

For your server, try simply removing that flag from the `blob-image` script — i.e. change the two instances of `-Zsq` to `-sq`. That should make PNG compression much more practical for you. :wink:
